### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by imdanielpiva** [Download/webdb#14]
Hi, there, I would like to know about the project, if it's going somewhere...

**Comment by Download** [comment]
Hi @imdanielpiva 
Thanks for your interest!

> I would like to know about the project, if it's going somewhere...

Not really no... :(
I still have ideas/plans for it but if I'm realistic these aren't happening any time soon.

There are some great web databases out there. [Pouchdb](https://pouchdb.com/) comes close to what I had in mind for this project but is coupled to CouchDB which you may not have/want.

Another interesting one imho is [Lovefield](https://google.github.io/lovefield/). Much more complete than webdb but no synch to a backend. But synch never really worked well in this project either so...

If you find another good substitute please let me know about. I'm still very much interested in this space.

**Comment by imdanielpiva** [comment]
Thanks for replaying, @Download!

Well, I've seen Pouchdb, but the fact of the necessity of using couchdb/couchbase, I cannot use it. I'll take a look at Lovefield.

Thanks anyway.
